from common import *

cmd = f'{CMAKE} -S . -B {BUILDDIR}/ngfx -DCMAKE_BUILD_TYPE={BUILD_TYPE} -G"{CMAKE_GENERATOR}" -DNGFX_GRAPHICS_BACKEND_{NGFX_GRAPHICS_BACKEND}=ON'
if OS == 'Windows':
    cmd += f' -DVCPKG_DIR=\'{VCPKG_DIR}\' -DCMAKE_SYSTEM_VERSION={CMAKE_SYSTEM_VERSION} -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING={CMAKE_MSVC_RUNTIME_LIBRARY}'

shell(cmd)
