name: 'tests Linux'

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:

jobs:
  linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        export OS=Linux
        bash build_scripts/install_deps.sh
        bash build_scripts/configure.sh
        bash build_scripts/build.sh
