name: 'tests Linux'

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:

jobs:
  linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        export OS=Linux
        sudo apt -y update
        sudo apt -y install ninja-build
        python3 build_scripts/install_deps.py && \
        python3 build_scripts/configure.py && \
        python3 build_scripts/build.py
