name: 'tests Mac'

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:

jobs:
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export OS=Darwin
        brew install bash
        /usr/local/bin/bash build_scripts/install_deps.sh
        /usr/local/bin/bash build_scripts/configure.sh
        /usr/local/bin/bash build_scripts/build.sh
