name: 'tests Mac'

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:

jobs:
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export OS=Darwin
        brew install bash coreutils ninja
        python3 build_scripts/install_deps.py && \
        python3 build_scripts/configure.py && \
        python3 build_scripts/build.py
