name: 'tests Windows'

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:

jobs:
  msvc:

    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          pip install meson
          .\build_scripts\windows\msvc-env.ps1
          .\build_scripts\windows\set_env.ps1
          python .\build_scripts\install_deps.py && `
          python .\build_scripts\configure.py && `
          python .\build_scripts\build.py

